version: '3'

tasks:
  install backend:
    dir: backend
    cmds:
      - poetry install --no-root
    
  install frontend:
    dir: frontend
    cmds:
      - npm install

  install:
    deps:
      - task: install frontend
      - task: install backend
