version: '3'

tasks:
  install backend:
    dir: backend
    cmds:
      - poetry install --no-root
    
  install frontend:
    dir: frontend
    cmds:
      - npm install

  install:
    deps:
      - task: install frontend
      - task: install backend

  frontend:
    dir: frontend
    cmds: 
      - |
        if [ -n "$ENV_FILE" ]; then
          source $ENV_FILE
          export $(grep -E '^VITE_' $ENV_FILE | xargs)
        fi
        npm run dev -- --https

  backend:
    dir: backend
    cmds:
    - |
      if [ -n "$ENV_FILE" ]; then
        source $ENV_FILE
        export $(grep -v '^#' $ENV_FILE | xargs)
      fi
      poetry run uvicorn app.main:app --reload --port 8080
  
  start:
    deps:
      - task: frontend
      - task: backend
  
  stop:
    cmds:
      - pkill -f "npm run dev"
      - pkill -f "uvicorn main:app --reload"

  test:
    cmds:
      - task: test:backend:unit
      - task: test:backend:integration
      - task: test:frontend

  test:backend:unit:
    dir: backend
    cmds:
    - |
      if [ -n "$ENV_FILE" ]; then
        source $ENV_FILE
        export $(grep -v '^#' $ENV_FILE | xargs)
      fi
      poetry run pytest app/tests/unit/ -v -s --html=app/tests/reports/unit/report.html

  test:backend:integration:
    dir: backend
    cmds:
    - |
      if [ -n "$ENV_FILE" ]; then
        source $ENV_FILE
        export $(grep -v '^#' $ENV_FILE | xargs)
      fi
      poetry run pytest app/tests/integration/ -v -s --html=app/tests/reports/integration/report.html

  test:frontend:
    dir: frontend
    cmds:
      - npm run test