version: '3'

tasks:
  install backend:
    dir: backend
    cmds:
      - poetry install --no-root
    
  install frontend:
    dir: frontend
    cmds:
      - npm install

  install:
    deps:
      - task: install frontend
      - task: install backend

  frontend:
    dir: frontend
    cmds: 
      - |
        if [ -n "$ENV_FILE" ]; then
          source $ENV_FILE
          export $(grep -E '^VITE_' $ENV_FILE | xargs)
        fi
        npm run dev -- --https

  backend:
    dir: backend
    cmds:
    - |
      if [ -n "$ENV_FILE" ]; then
        source $ENV_FILE
        export $(grep -v '^#' $ENV_FILE | xargs)
      fi
      poetry run uvicorn main:app --reload
  
  start:
    deps:
      - task: frontend
      - task: backend
  
  stop:
    cmds:
      - pkill -f "npm run dev"
      - pkill -f "uvicorn main:app --reload"